ALTER TABLE "IgExamplePost"
  ADD COLUMN "objectKey" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "fileName" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "mimeType" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "fileSize" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "styleSummary" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "summaryStatus" TEXT NOT NULL DEFAULT 'pending',
  ADD COLUMN "summaryBatchId" TEXT,
  ADD COLUMN "summaryError" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
