name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # Usa el nombre del repositorio como nombre de la imagen

jobs:
  build-and-push-docker:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write # Necesario para escribir en GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=sha
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: . # El contexto de construcción, usualmente el directorio raíz del repositorio
          file: ./Dockerfile # Ruta a tu Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          #cache-from: type=gha # Habilita el caché para construcciones más rápidas
          #cache-to: type=gha,mode=max # Guarda el caché para futuras construcciones
